CODES = {
    "en": {
        "AUD": "Australian Dollar",
        "BYN": "Belarusian Ruble",
        "BRL": "Brazilian Real",
        "CAD": "Canadian Dollar",
        "CNY": "Chinese Yuan",
        "CZK": "Czech Koruna",
        "EUR": "Euro",
        "HKD": "Hong Kong Dollar",
        "INR": "Indian Rupee",
        "JPY": "Japanese Yen",
        "KZT": "Kazakhstani Tenge",
        "PKR": "Pakistani Rupee",
        "GBP": "Pound sterling",
        "RUB": "Russian Ruble",
        "SAR": "Saudi Riyal",
        "SGD": "Singapore Dollar",
        "KRW": "South Korean won",
        "CHF": "Swiss Franc",
        "TJS": "Tajikistani Somoni",
        "TRY": "Turkish lira",
        "UAH": "Ukrainian hryvnia",
        "AED": "United Arab Emirates Dirham",
        "USD": "United States Dollar",
        "UZS": "Uzbekistani Sum"
    },
    "ru": {
        "AUD": "Австралийский доллар",
        "BYN": "Белорусский рубль",
        "BRL": "Бразильский реал",
        "CAD": "Канадский доллар",
        "CNY": "Китайский юань",
        "CZK": "Чешская крона",
        "EUR": "Евро",
        "HKD": "Гонконгский доллар",
        "INR": "Индийская рупия",
        "JPY": "Японская иена",
        "KZT": "Казахстанский тенге",
        "PKR": "Пакистанская рупия",
        "GBP": "Фунт стерлингов",
        "RUB": "Российский рубль",
        "SAR": "Саудовский риал",
        "SGD": "Сингапурский доллар",
        "KRW": "Южнокорейский вон",
        "CHF": "Швейцарский франк",
        "TJS": "Таджикистанские сомони",
        "TRY": "Tурецкая лира",
        "UAH": "Украинская гривна",
        "AED": "Дирхам ОАЭ",
        "USD": "Доллар США",
        "UZS": "Узбекский сум",
    }
}
